datadir: ""  # Defaults to Covid.jl/data. Must contain directories input and output.
input_data:
    params:                       "params.tsv"
    age_distribution:             "population_by_age.tsv"
    workplace_distribution:       "workplace_by_size.tsv"
    primaryschool_distribution:   "avg_yearlevel_size_distribution_primary.tsv"
    secondaryschool_distribution: "avg_yearlevel_size_distribution_secondary.tsv"
    household_distribution:       "households.tsv"
firstday: 2020-01-25  # Simulation starts at 12am.
lastday:  2021-01-01  # Simulation finishes at 12am
nruns: 100
initial_status_counts: {E: 1}

# The physical distancing policy.
# The numbers are Pr(Contact a person in the contact list during any given day)
distancing_policy:
    2020-01-25: {household: 0.5, school: 0.2, workplace: 0.2, community: 0.1, social: 0.1}  # Normal.
    2020-03-23: {household: 0.5, school: 0.2, workplace: 0.001, community: 0.01, social: 0.01}  # Stage 1: Bars/restaurants/gyms/cinemas
    2020-03-24: {household: 0.5, school: 0.2, workplace: 0.001, community: 0.01, social: 0.01}  # School closures
    2020-03-25: {household: 0.5, school: 0.002, workplace: 0.001, community: 0.0001, social: 0.0001}  # Stage 2: Recreation, entertainment, retail, weddings/funerals.
    2020-03-30: {household: 0.5, school: 0.002, workplace: 0.001, community: 0.0001, social: 0.0001}  # Stage 3: Gatherings of <=2
    2020-04-27: {household: 0.5, school: 0.002, workplace: 0.001, community: 0.04, social: 0.04}     # Social/community impatience
    2020-05-25: {household: 0.5, school: 0.1, workplace: 0.001, community: 0.04, social: 0.04}  # Schools partially reopen
    2020-05-30: {household: 0.5, school: 0.1, workplace: 0.001, community: 0.04, social: 0.06}  # Small gatherings at home
    2020-06-09: {household: 0.5, school: 0.2, workplace: 0.001, community: 0.04, social: 0.06}  # Schools fully reopen (Tue after Queen's Birthday)
    2020-06-15: {household: 0.5, school: 0.2, workplace: 0.2, community: 0.1, social: 0.1}      # Scenario: Normal

# Pr(Test | Person is not a contact of a known case, status)
# Typically only people who are symptomatic and satisfy other criteria are tested
testing_policy:
    2020-01-25: {IS: 0.3, W: 1.0}
    2020-04-27: {IS: 0.8, W: 1.0}  # Testing blitz
    2020-05-25: {IS: 0.3, W: 1.0}  # Resume normal testing

# Pr(Test | Person is a contact of a known case, status)
# Asymptomatic contacts are S, E, IA or R.
# Symptomatic contacts are IS because W, ICU and V patients have already been tested upon admission to hospital.
tracing_policy:
    2020-01-25: {household: {symptomatic: 1.0, asymptomatic: 0.0}, school: {symptomatic: 0.0, asymptomatic: 0.0}, workplace: {symptomatic: 0.0, asymptomatic: 0.0}, community: {symptomatic: 0.0, asymptomatic: 0.0}, social: {symptomatic: 0.0, asymptomatic: 0.0}}
    2020-03-25: {household: {symptomatic: 1.0, asymptomatic: 0.0}, school: {symptomatic: 1.0, asymptomatic: 0.0}, workplace: {symptomatic: 1.0, asymptomatic: 0.0}, community: {symptomatic: 0.0, asymptomatic: 0.0}, social: {symptomatic: 0.0, asymptomatic: 0.0}}
    2020-05-04: {household: {symptomatic: 1.0, asymptomatic: 0.0}, school: {symptomatic: 1.0, asymptomatic: 0.0}, workplace: {symptomatic: 1.0, asymptomatic: 1.0}, community: {symptomatic: 1.0, asymptomatic: 0.0}, social: {symptomatic: 1.0, asymptomatic: 0.0}}
#    2020-06-15: {household: {symptomatic: 1.0, asymptomatic: 1.0}, school: {symptomatic: 1.0, asymptomatic: 1.0}, workplace: {symptomatic: 1.0, asymptomatic: 1.0}, community: {symptomatic: 1.0, asymptomatic: 1.0}, social: {symptomatic: 1.0, asymptomatic: 1.0}}

# People who are awaiting test results are quarantined until the result is available, which is currently 2 days after the test date.
# People who test positive are quarantined for X days after onset of symptoms if they are symptomatic (status=IS), or X days after the test date if asymptomatic.
# People known to be in recent contact with a known case are quarantined for X days.
quarantine_policy:
    2020-01-25: {awaiting_test_result: {days: 2, compliance: 0.7}, tested_positive: {days: 10, compliance: 0.7}, case_contacts: {household: {days: 14, compliance: 0.7}}}
    2020-03-15: {awaiting_test_result: {days: 2, compliance: 0.7}, tested_positive: {days: 10, compliance: 0.7}, case_contacts: {household: {days: 14, compliance: 0.7}, workplace: {days: 14, compliance: 0.7}}}
#    2020-06-15: {awaiting_test_result: {days: 2, compliance: 0.7}, tested_positive: {days: 14, compliance: 0.7},
#                 case_contacts: {household: {days: 14, compliance: 0.7}, workplace: {days: 14, compliance: 0.7}, school: {days: 14, compliance: 0.7}, community: {days: 14, compliance: 0.7}, social: {days: 14, compliance: 0.7}}}
