datadir: "C:\\projects\\data\\dhhs\\covid-abm"
#datadir: "C:\\Users\\jlaw1812\\data\\covid-abm"
input_data:
    params:                       "params.tsv"
    age_distribution:             "population_by_age_VIC.tsv"
    workplace_distribution:       "workplace_by_size_VIC.tsv"
    primaryschool_distribution:   "avg_yearlevel_size_distribution_primary.tsv"
    secondaryschool_distribution: "avg_yearlevel_size_distribution_secondary.tsv"
    household_distribution:       "households.tsv"
maxtime: 180
nruns: 3
initial_status_counts: {E: 1}

# The distancing regime is the physical distancing policy.
# The number are Pr(Contact a person in the contact list during any given day)
distancing_regime:
    0:  {household: 0.5, school: 0.2, workplace: 0.2, community: 0.1, social: 0.1}  # 26th Feb. Normal.
    18: {household: 0.5, school: 0.2, workplace: 0.001, community: 0.01, social: 0.01}  # 15th Mar. Business restrictions.
    28: {household: 0.5, school: 0.002, workplace: 0.001, community: 0.0001, social: 0.0001}  # 25th Mar. Stage 2 restrictions + school closures.

# The testing regime is the policy for testing people not known to be contacts of a known case.
# Typically only people who are symptomatic and satisfy other criteria are tested
# The numbers are Pr(Test the person | status)
testing_regime:
    0: {IS: 0.9, W: 1.0}

# The tracing regime is the policy for testing contacts of a known case.
# The numbers are Pr(Test a contact of a positive case).
# Asymptomatic contacts are S, E, IA or R.
# In the context of tracing all symptomatic cases are IS because W, ICU and V patients have already been tested upon admission to the ward.
tracing_regime:
    0: {household: {symptomatic: 1.0, asymptomatic: 0.0}, school: {symptomatic: 1.0, asymptomatic: 0.0}, workplace: {symptomatic: 1.0, asymptomatic: 1.0},
        community: {symptomatic: 1.0, asymptomatic: 0.0}, social: {symptomatic: 1.0, asymptomatic: 0.0}}

# The quarantine regime is the policy for isolating people.
quarantine_regime:
    0: {known_contacts: {days: 14, compliance: 0.8}, tested: {days: 2, compliance: 0.8}, positive: {days: 10 days after entering IS, or 10 days after test date if IA, compliance: 0.8}}
