datadir: "C:\\projects\\data\\dhhs\\covid-abm"
#datadir: "C:\\Users\\jlaw1812\\data\\covid-abm"
input_data:
    params:                       "params.tsv"
    age_distribution:             "population_by_age_VIC.tsv"
    workplace_distribution:       "workplace_by_size_VIC.tsv"
    primaryschool_distribution:   "avg_yearlevel_size_distribution_primary.tsv"
    secondaryschool_distribution: "avg_yearlevel_size_distribution_secondary.tsv"
    household_distribution:       "households.tsv"
firstday: 2020-02-26  # Simulation starts at 12am
lastday:  2020-09-01  # Simulation finishes at 12am
nruns: 3
initial_status_counts: {E: 1}

# The distancing regime is the physical distancing policy.
# The numbers are Pr(Contact a person in the contact list during any given day)
distancing_regime:
    2020-02-26: {household: 0.5, school: 0.2, workplace: 0.2, community: 0.1, social: 0.1}  # Normal.
    2020-03-15: {household: 0.5, school: 0.2, workplace: 0.001, community: 0.01, social: 0.01}  # Business restrictions.
    2020-03-25: {household: 0.5, school: 0.002, workplace: 0.001, community: 0.0001, social: 0.0001}  # Stage 2 restrictions + school closures.

# The testing regime is the policy for testing people not known to be contacts of a known case.
# Pr(Test | Person is not a contact of a known case, status)
# Typically only people who are symptomatic and satisfy other criteria are tested
testing_regime:
    2020-02-26: {IS: 0.9, W: 1.0}

# Pr(Test | Person is a contact of a known case, status)
# Asymptomatic contacts are S, E, IA or R.
# Symptomatic cases are IS because W, ICU and V patients have already been tested upon admission to hospital.
tracing_regime:
    2020-02-26: {household: {symptomatic: 1.0, asymptomatic: 0.0}, school: {symptomatic: 1.0, asymptomatic: 0.0}, workplace: {symptomatic: 1.0, asymptomatic: 1.0}, community: {symptomatic: 1.0, asymptomatic: 0.0}, social: {symptomatic: 1.0, asymptomatic: 0.0}}

# The quarantine regime is the policy for isolating people.
# People who are awaiting test results are quarantined until the result is available, which is currently 2 days after the test date.
# People who test positive are quarantined for X days after onset of symptoms if they are symptomatic (status=IS), or X days after the test date if asymptomatic.
# People known to be in recent contact with a known case are quarantined for X days.
quarantine_regime:
    2020-02-26: {awaiting_test_result: {days: 2, compliance: 0.7}, tested_positive: {days: 10, compliance: 0.7}, case_contacts: {workplace: {days: 14, compliance: 0.7}}}
