output_directory: "C:\\projects\\data\\dhhs\\covid-abm\\output"
input_data:
    params:                 "C:\\projects\\data\\dhhs\\covid-abm\\input\\consumable\\params.tsv"
    age_distribution:       "C:\\projects\\data\\dhhs\\covid-abm\\input\\consumable\\population_by_age_VIC.tsv"
    household_distribution: "C:\\projects\\data\\dhhs\\covid-abm\\input\\consumable\\household_distribution.csv"
    workplace_distribution: "C:\\projects\\data\\dhhs\\covid-abm\\input\\consumable\\workplace_by_size_VIC.tsv"
    primaryschool_distribution:   "C:\\projects\\data\\dhhs\\covid-abm\\input\\consumable\\avg_yearlevel_size_distribution_primary.tsv"
    secondaryschool_distribution: "C:\\projects\\data\\dhhs\\covid-abm\\input\\consumable\\avg_yearlevel_size_distribution_secondary.tsv"
maxtime: 180
nruns_per_scenario: 4
initial_state_distribution: [0.98, 0.02, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # SEIHCVRD
scenarios:
    #open: {household: 1.0, school: 1.0, workplace: 1.0, community: 1.0, social: 1.0}
    #home: {household: 1.0, school: 0.0, work: 0.0, community: 0.1, social: 0.0}
    social_only:
        0: {household: 1.0, school: 0.0, workplace: 0.0, community: 0.0, social: 0.0}
        15: {household: 1.0, school: 1.0, workplace: 1.0, community: 1.0, social: 1.0}
